// Auto-generated by scan-records.js — do not edit by hand.
window.RECORDS = {
  "Meltemi": {
    "2022-11-23": [
      "Sail records/Meltemi/2022-11-23/SESSION_1.VTK",
      "Sail records/Meltemi/2022-11-23/SESSION_2.VTK"
    ],
    "2022-11-28": [
      "Sail records/Meltemi/2022-11-28/SESSION_1.VTK"
    ],
    "2022-12-01": [
      "Sail records/Meltemi/2022-12-01/SESSION_1.VTK",
      "Sail records/Meltemi/2022-12-01/SESSION_2.VTK",
      "Sail records/Meltemi/2022-12-01/SESSION_3.VTK",
      "Sail records/Meltemi/2022-12-01/SESSION_4.VTK",
      "Sail records/Meltemi/2022-12-01/SESSION_5.VTK",
      "Sail records/Meltemi/2022-12-01/SESSION_6.VTK"
    ],
    "2022-12-03": [
      "Sail records/Meltemi/2022-12-03/SESSION_1.VTK"
    ],
    "2023-02-05": [
      "Sail records/Meltemi/2023-02-05/SESSION_1.VTK",
      "Sail records/Meltemi/2023-02-05/SESSION_2.VTK"
    ],
    "2023-03-04": [
      "Sail records/Meltemi/2023-03-04/SESSION_1.VTK"
    ],
    "2023-03-11": [
      "Sail records/Meltemi/2023-03-11/SESSION_1.VTK"
    ],
    "2023-03-14": [
      "Sail records/Meltemi/2023-03-14/SESSION_1.VTK"
    ],
    "2023-04-01": [
      "Sail records/Meltemi/2023-04-01/SESSION_1.VTK"
    ],
    "2023-09-23": [
      "Sail records/Meltemi/2023-09-23/SESSION_1.VTK"
    ],
    "2023-10-21": [
      "Sail records/Meltemi/2023-10-21/SESSION_1.VTK"
    ],
    "2023-11-04": [
      "Sail records/Meltemi/2023-11-04/SESSION_1.VTK"
    ],
    "2023-12-16": [
      "Sail records/Meltemi/2023-12-16/SESSION_1.VTK",
      "Sail records/Meltemi/2023-12-16/SESSION_2.VTK",
      "Sail records/Meltemi/2023-12-16/SESSION_3.VTK",
      "Sail records/Meltemi/2023-12-16/SESSION_4.VTK"
    ],
    "2024-01-06": [
      "Sail records/Meltemi/2024-01-06/SESSION_1.VTK",
      "Sail records/Meltemi/2024-01-06/SESSION_2.VTK",
      "Sail records/Meltemi/2024-01-06/SESSION_3.VTK",
      "Sail records/Meltemi/2024-01-06/SESSION_4.VTK",
      "Sail records/Meltemi/2024-01-06/SESSION_5.VTK",
      "Sail records/Meltemi/2024-01-06/SESSION_6.VTK",
      "Sail records/Meltemi/2024-01-06/SESSION_7.VTK"
    ],
    "2024-01-20": [
      "Sail records/Meltemi/2024-01-20/SESSION_1.VTK",
      "Sail records/Meltemi/2024-01-20/SESSION_2.VTK",
      "Sail records/Meltemi/2024-01-20/SESSION_3.VTK",
      "Sail records/Meltemi/2024-01-20/SESSION_4.VTK"
    ],
    "2024-01-28": [
      "Sail records/Meltemi/2024-01-28/SESSION_1.VTK"
    ],
    "2024-02-17": [
      "Sail records/Meltemi/2024-02-17/SESSION_1.VTK"
    ],
    "2024-02-24": [
      "Sail records/Meltemi/2024-02-24/SESSION_1.VTK"
    ],
    "2024-03-16": [
      "Sail records/Meltemi/2024-03-16/SESSION_1.VTK",
      "Sail records/Meltemi/2024-03-16/SESSION_2.VTK"
    ],
    "2024-03-23": [
      "Sail records/Meltemi/2024-03-23/SESSION_1.VTK"
    ],
    "2024-04-20": [
      "Sail records/Meltemi/2024-04-20/SESSION_1.VTK"
    ],
    "2024-05-05": [
      "Sail records/Meltemi/2024-05-05/SESSION_1.VTK"
    ],
    "2024-09-14": [
      "Sail records/Meltemi/2024-09-14/SESSION_1.VTK"
    ],
    "2024-10-05": [
      "Sail records/Meltemi/2024-10-05/SESSION_1.VTK"
    ],
    "2024-10-19": [
      "Sail records/Meltemi/2024-10-19/SESSION_1.VTK"
    ],
    "2024-11-23": [
      "Sail records/Meltemi/2024-11-23/SESSION_1.VTK"
    ],
    "2024-12-07": [
      "Sail records/Meltemi/2024-12-07/SESSION_1.VTK"
    ],
    "2024-12-14": [
      "Sail records/Meltemi/2024-12-14/SESSION_1.VTK"
    ],
    "2025-02-22": [
      "Sail records/Meltemi/2025-02-22/SESSION_1.VTK"
    ],
    "2025-03-01": [
      "Sail records/Meltemi/2025-03-01/SESSION_1.VTK"
    ],
    "2025-03-02": [
      "Sail records/Meltemi/2025-03-02/SESSION_1.VTK"
    ],
    "2025-03-15": [
      "Sail records/Meltemi/2025-03-15/SESSION_1.VTK"
    ],
    "2025-03-22": [
      "Sail records/Meltemi/2025-03-22/SESSION_1.VTK"
    ],
    "2025-03-30": [
      "Sail records/Meltemi/2025-03-30/SESSION_1.VTK"
    ],
    "2025-04-12": [
      "Sail records/Meltemi/2025-04-12/SESSION_1.VTK"
    ],
    "2025-04-26": [
      "Sail records/Meltemi/2025-04-26/SESSION_1.VTK"
    ],
    "2025-08-06": [
      "Sail records/Meltemi/2025-08-06/SESSION_1.VTK",
      "Sail records/Meltemi/2025-08-06/SESSION_2.VTK"
    ],
    "2025-10-18": [
      "Sail records/Meltemi/2025-10-18/SESSION_1.VTK"
    ],
    "2025-10-25": [
      "Sail records/Meltemi/2025-10-25/SESSION_1.VTK"
    ],
    "2025-11-01": [
      "Sail records/Meltemi/2025-11-01/SESSION_1.VTK"
    ],
    "2025-11-08": [
      "Sail records/Meltemi/2025-11-08/SESSION_1.VTK"
    ],
    "2026-01-18": [
      "Sail records/Meltemi/2026-01-18/SESSION_1.VTK"
    ],
    "2026-01-24": [
      "Sail records/Meltemi/2026-01-24/SESSION_1.VTK"
    ],
    "2026-02-07": [
      "Sail records/Meltemi/2026-02-07/SESSION_1.VTK"
    ],
    "2026-02-08": [
      "Sail records/Meltemi/2026-02-08/SESSION_1.VTK"
    ],
    "2026-03-07": [
      "Sail records/Meltemi/2026-03-07/SESSION_1.VTK"
    ],
    "2026-03-21": [
      "Sail records/Meltemi/2026-03-21/SESSION_1.VTK"
    ],
    "2026-03-28": [
      "Sail records/Meltemi/2026-03-28/SESSION_1.VTK"
    ],
    "2026-04-11": [
      "Sail records/Meltemi/2026-04-11/SESSION_1.VTK"
    ]
  }
};
