// Scans `Sail records/<Boat>/<YYYY-MM-DD>/*.VTK` and writes records.js
// (consumed by the app at startup so it auto-loads everything without a picker).
//
// Run on its own:   node scan-records.js
// Or via start.cjs (which is what the dev server uses).

const fs = require("fs");
const path = require("path");

// VTK records live under ./Sail records/<Boat>/<YYYY-MM-DD>/*.VTK
// For a Dropbox/Drive shared fleet folder, replace this directory with a
// symlink to the synced cloud folder — see CLOUD-SETUP.md.
const ROOT = path.join(__dirname, "Sail records");

function listDirs(p) {
  if (!fs.existsSync(p)) return [];
  return fs.readdirSync(p, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

function listVtk(p) {
  if (!fs.existsSync(p)) return [];
  return fs.readdirSync(p, { withFileTypes: true })
    .filter((e) => e.isFile() && /\.vtk$/i.test(e.name))
    .map((e) => e.name)
    .sort();
}

const records = {};
for (const boat of listDirs(ROOT)) {
  const boatDir = path.join(ROOT, boat);
  const days = {};
  for (const day of listDirs(boatDir)) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(day)) continue;
    const sessions = listVtk(path.join(boatDir, day))
      .map((f) => `Sail records/${boat}/${day}/${f}`);
    if (sessions.length) days[day] = sessions;
  }
  if (Object.keys(days).length) records[boat] = days;
}

const out = `// Auto-generated by scan-records.js — do not edit by hand.
window.RECORDS = ${JSON.stringify(records, null, 2)};
`;
fs.writeFileSync(path.join(__dirname, "records.js"), out);

const counts = Object.entries(records).map(([b, ds]) => {
  const total = Object.values(ds).reduce((n, l) => n + l.length, 0);
  return `${b}: ${Object.keys(ds).length} days / ${total} sessions`;
});
console.log("Wrote records.js — " + (counts.join(" · ") || "no records found"));
