// Merges Lamma Island daily wind direction + speed CSVs from HKO
// into a single JS file consumed by the app.
//
// Usage (from the Sailing/ folder):
//   node wind/build.js
//
// Refresh the underlying CSVs first if you want fresh data:
//   curl -sL https://data.weather.gov.hk/cis/csvfile/LAM/ALL/daily_LAM_PDIR_ALL.csv -o wind/lamma_dir.csv
//   curl -sL https://data.weather.gov.hk/cis/csvfile/LAM/ALL/daily_LAM_WSPD_ALL.csv -o wind/lamma_speed.csv

const fs = require("fs");
const path = require("path");

function parse(file) {
  // CSV columns: Year, Month, Day, Value, Completeness
  // First two lines are header text in zh + en, third is the column header.
  const text = fs.readFileSync(file, "utf8").replace(/^\uFEFF/, "");
  const lines = text.split(/\r?\n/);
  const out = new Map();
  for (const line of lines) {
    const m = line.match(/^(\d{4}),(\d{1,2}),(\d{1,2}),([\d.]+),([A-Z])\s*$/);
    if (!m) continue;
    const [, y, mo, d, v, flag] = m;
    const key = `${y}-${mo.padStart(2, "0")}-${d.padStart(2, "0")}`;
    out.set(key, { v: Number(v), flag });
  }
  return out;
}

const dir = parse(path.join(__dirname, "lamma_dir.csv"));
const spd = parse(path.join(__dirname, "lamma_speed.csv"));

// Take the union; either field may be missing on a given day.
const days = new Set([...dir.keys(), ...spd.keys()]);
const merged = {};
for (const day of [...days].sort()) {
  const d = dir.get(day);
  const s = spd.get(day);
  merged[day] = {
    dir: d ? d.v : null,         // degrees, FROM which the wind blows
    speed: s ? s.v : null,        // km/h
    flag: (d && s) ? d.flag : (d?.flag || s?.flag || null),
  };
}

const stations = {
  // HKO weather station Lamma Island
  LAM: { name: "Lamma Island", lat: 22.2118, lon: 114.1167 },
};

const out = `// Auto-generated by wind/build.js — do not edit by hand.
// Source: Hong Kong Observatory daily prevailing wind direction + mean wind speed.
window.WIND_STATIONS = ${JSON.stringify(stations, null, 2)};
window.WIND_DAILY = ${JSON.stringify(merged)};
`;
fs.writeFileSync(path.join(__dirname, "lamma.js"), out);
console.log(`Wrote wind/lamma.js — ${Object.keys(merged).length} days`);
