// Walks wind/text/<YYYY-MM-DD>/<HH>.txt and writes wind/timeseries.js, the
// app-side manifest of per-station hourly readings.
//
// Output:
//   window.WIND_STATIONS  = { "Lamma Island": "Lamma Island", ... }
//   window.WIND_HOURLY    = { "YYYY-MM-DD": { "Lamma Island": [
//                              { h: 12, dir: "Southeast", spd: 7, gust: 18 }, ...
//                            ] } }
// Direction values are the strings HKO publishes (e.g. "East", "Southeast",
// "Variable", "N/A"); spd/gust are km/h numbers (or null for "N/A").

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "text");

// HKO direction names → degrees (where the wind is coming FROM).
// "Variable" / "N/A" yield null.
const DIR_DEG = {
  "North": 0, "Northeast": 45, "East": 90, "Southeast": 135,
  "South": 180, "Southwest": 225, "West": 270, "Northwest": 315,
};

function parseSnapshot(text) {
  // Strip HTML tags so we can match the plain-text table.
  const plain = text.replace(/<[^>]+>/g, "");
  const m = plain.match(/10-Minute Mean Wind Direction[^\n]*\n([\s\S]*?)\n\s*\n/);
  if (!m) return null;
  const rows = {};
  for (const line of m[1].split(/\r?\n/)) {
    // Station names are 1-3 words ending before a 2-space gap; direction is
    // a word; then mean speed (int or N/A); then gust (int or N/A).
    const r = line.match(/^([A-Z][\w' ]+?)\s{2,}(N\/A|North|Northeast|East|Southeast|South|Southwest|West|Northwest|Variable)\s+(\d+|N\/A)\s+(\d+|N\/A)\s*$/);
    if (!r) continue;
    const [, name, dir, spd, gust] = r;
    rows[name.trim()] = {
      dir: dir === "N/A" ? null : dir,
      deg: DIR_DEG[dir] ?? null,
      spd: spd === "N/A" ? null : Number(spd),
      gust: gust === "N/A" ? null : Number(gust),
    };
  }
  return rows;
}

function listDirs(p) {
  if (!fs.existsSync(p)) return [];
  return fs.readdirSync(p, { withFileTypes: true })
    .filter((e) => e.isDirectory()).map((e) => e.name).sort();
}

const hourly = {}; // date -> station -> [{h, dir, deg, spd, gust}]
const stationsSeen = new Set();
let snapshots = 0;

for (const date of listDirs(ROOT)) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) continue;
  const dayDir = path.join(ROOT, date);
  for (const f of fs.readdirSync(dayDir).sort()) {
    const m = f.match(/^(\d{2})\.txt$/);
    if (!m) continue;
    const h = Number(m[1]);
    const text = fs.readFileSync(path.join(dayDir, f), "utf8");
    const rows = parseSnapshot(text);
    if (!rows) continue;
    snapshots++;
    if (!hourly[date]) hourly[date] = {};
    for (const [station, vals] of Object.entries(rows)) {
      stationsSeen.add(station);
      if (!hourly[date][station]) hourly[date][station] = [];
      hourly[date][station].push({ h, ...vals });
    }
  }
}

// Sort each station's readings by hour (defensive).
for (const date of Object.keys(hourly)) {
  for (const s of Object.keys(hourly[date])) {
    hourly[date][s].sort((a, b) => a.h - b.h);
  }
}

const stations = {};
for (const s of [...stationsSeen].sort()) stations[s] = s;

const out = `// Auto-generated by wind/scan-text.js — do not edit by hand.
// Source: HKO Past 24-Hours Regional Weather text snapshots (hourly).
window.WIND_STATIONS = ${JSON.stringify(stations)};
window.WIND_HOURLY = ${JSON.stringify(hourly)};
`;
fs.writeFileSync(path.join(__dirname, "timeseries.js"), out);
console.log(`Wrote wind/timeseries.js — ${Object.keys(hourly).length} day(s), ${snapshots} snapshots, ${stationsSeen.size} stations`);
